Add commonjs files to the dist output
react-dnd/react-dnd pull request #3526
Opened 2022-12-06 15:58 UTC by ricsam

This will make the packages compatible with both commonjs and esm.

This method is explained [here](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html), which is compatible with current tooling.

This would for example resolve these issues:
https://github.com/react-dnd/react-dnd/issues/3521
https://github.com/react-dnd/react-dnd/issues/3518
https://github.com/react-dnd/react-dnd/issues/3443
https://github.com/react-dnd/react-dnd/issues/3454

and plenty more.

I've not bumped the version in the packages.

I've tested this by publishing these packages to our private registry. We use typescript and ESM as well as jest and commonjs and this resolved the issues.

2022-12-06 20:31 UTC, ricsam commented
The way the dependency semvers are setup we need to bump everything with a major version in order to merge something like this

2023-01-08 14:45 UTC, ricsam commented
I bumped all the versions to a new major version

2023-01-19 09:09 UTC, macrozone commented
would be nice to have this merged as it would solve https://github.com/react-page/react-page/issues/1190

2023-01-19 12:29 UTC, brandstetterm commented
I also would appreciate it if this pull request would get merged

2023-01-19 17:25 UTC, darthtrevino requested changes
I kind of balked at this PR at first, since a lot of work went into making this work with ESM. But I understand that shipping dual-mode makes life easier in a lot of cases. 

I'll need to verify that these libraries can be required() in a CommonJS context before release.

2023-01-19 17:25 UTC, darthtrevino commented on packages/backend-html5/package.json
> +  "version": "17.0.0",
We're using the `yarn version` plugin. The mechanism for a bump is to use `yarn version check --interactive` to create a semver impact document, which is resolved at release time.

2023-01-19 17:25 UTC, darthtrevino commented on packages/backend-html5/package.json
> +    "add_pkgjson": "node ../../scripts/createDistPackageJson.mjs",
What is the purpose of this script?

2023-01-19 17:45 UTC, ricsam commented on packages/backend-html5/package.json
> +    "add_pkgjson": "node ../../scripts/createDistPackageJson.mjs",
This will create a package.json file in the dist folders. That is needed for the resolution algorithms to find the correct package, as described [here](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html). The same method is used by plenty of packages. On top of my head I know react-icons and mui uses this approach

2023-01-19 19:34 UTC, darthtrevino approved these changes

2023-01-19 19:35 UTC, darthtrevino approved these changes

2023-01-19 19:35 UTC, merged

2023-01-19 20:36 UTC, brandstetterm commented
> I kind of balked at this PR at first, since a lot of work went into making this work with ESM. But I understand that shipping dual-mode makes life easier in a lot of cases. 
> 
> 
> 
> I'll need to verify that these libraries can be required() in a CommonJS context before release.

Thank you very much for merging it. When can we expect it to be in a release?

2023-01-26 15:02 UTC, joulev commented
Second this. I think now is a good time to release a new version.

2023-02-28 13:20 UTC, NiclasThobaben commented
> > I kind of balked at this PR at first, since a lot of work went into making this work with ESM. But I understand that shipping dual-mode makes life easier in a lot of cases.
> > I'll need to verify that these libraries can be required() in a CommonJS context before release.
> 
> Thank you very much for merging it. When can we expect it to be in a release?

Is there any information on when this change is available?

2023-04-24 21:29 UTC, gdostie commented
Hello @darthtrevino, I think these changes would help quite a few people. Any plans to release those changes on npm soon?

2023-07-11 05:11 UTC, thenano commented
Just following up to see when this could be released? I really do appreciate all the hard work that goes into maintaining an open source package and I thank everyone involved so far for creating such a great library! I'm happy to offer any help needed to move this along, we've been waiting for this release for a while now in order to upgrade all of our dnd dependencies.

Thanks again!

2023-10-19 13:49 UTC, SimonHoskinsBP commented
Any news on release for this?

2023-11-17 15:33 UTC, FabioCingottini commented
Really need this fix, any news?

2024-01-26 09:53 UTC, JR0210 commented
Is there going to be a release for this anytime soon? I'm trying to update an outdated React project